[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]#, "-Ctarget-feature=+crt-static"]

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y", "-Ctarget-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=/opt/homebrew/bin/zld", "-Zshare-generics=y", "-Ctarget-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
rustflags = ["-Ctarget-feature=+crt-static"]
